### ISSUE TITLE
UI exception

### ISSUE THREAD

**Issue by hotfics** [zongzhengli/absolute-zero#1]
When I start computer vs computer  with a search depth 9,throws an exception .
Not always ,but frequently

"发生了 System.InvalidOperationException
  HResult=0x80131509
  Message=集合已修改；可能无法执行枚举操作。
  Source=<无法计算异常源>
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at AbsoluteZero.VisualPosition.DrawPieces(Graphics g) in D:\openSource\absolute-zero\Source\Visuals\VisualPosition.cs:line 251
   at AbsoluteZero.Game.Draw(Graphics g) in D:\openSource\absolute-zero\Source\Gameplay\Game.cs:line 215
   at AbsoluteZero.Window.DrawHandler(Object sender, PaintEventArgs e) in D:\openSource\absolute-zero\Source\Interface\Window.cs:line 93
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Form.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
"

**Comment by zongzhengli** [comment]
This was fixed by https://github.com/zongzhengli/absolute-zero/commit/c9a6ef6f9651db609f5a6ca59bea31b014402447
